{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7772fde5-c814-4dbc-a330-2da90dbb320c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Explain the key features of python that make it a popular choice for programming.\n",
    "\n",
    "# Python is popular programming language due to several key features...\n",
    "#Easy to learn\n",
    "#free and open source\n",
    "#large standard library\n",
    "#object oriented programming\n",
    "#large community and support\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "234677f4-254d-45cd-8ea3-834698c221aa",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Describe the role of predefined keywords in python and provide examples of how they are used  in a program.\n",
    "\n",
    "#They help define the syntax and structure of the language , here are some essential python keywords and their roles..\n",
    "conditional statement\n",
    "# if \n",
    "# elif \n",
    "# else\n",
    "some examples\n",
    "weather = \"rainny\"\n",
    "if weather == \"rainny\"\n",
    "    print (\"i will not play cricket\")\n",
    "    \n",
    "loop statement\n",
    "# for \n",
    "# while\n",
    "ex:\n",
    "    count =5\n",
    "    while count >0:\n",
    "        print (count)\n",
    "        count =count-1\n",
    " control statement\n",
    "#break\n",
    "#continue\n",
    "ex:\n",
    "    n = 7\n",
    "    i = 1 \n",
    "    while i<n:\n",
    "        print (i)\n",
    "        i =i+1\n",
    "        if i ==3:\n",
    "            break\n",
    "    else :\n",
    "        print (\"this will be excuted when the while is run succefuly without any break\")\n",
    "        \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0bfeda59-622e-4a4b-9681-6e18561dc9cc",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Compare and contrast mutable and immutable objects in python witn examples.\n",
    "Mutable objects\n",
    "# list ('list')\n",
    "# dictionaries ('dict')\n",
    "# sets ('set')\n",
    "ex:\n",
    "    my_list = [1, 2, 3]\n",
    "    print(my_list)  # [1, 2, 3]\n",
    "    my_list.append(4)\n",
    "    print (my_list)  #[1, 2, 3, 4]\n",
    "\n",
    "Immutable objects\n",
    "# integers('int')\n",
    "#float('float')\n",
    "#string('str')\n",
    "#tuples('tuple')\n",
    "#boolean value('bool')\n",
    "ex:\n",
    "    my_string =\"hello\"\n",
    "    print(my_string)\n",
    "    my_string += \"world\"\n",
    "    print(my_string)\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7aa255e7-0dac-4721-893e-ca16c39c6089",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Discuss the different types of operators in python and provide examples of how they are used.\n",
    "\n",
    "# in python operators are special symbols used to perform operations on variables and values.\n",
    "types of operators\n",
    "#Arithmetic operators\n",
    "addition:\n",
    "    5+7=12\n",
    "subtraction:\n",
    "    4-2=2\n",
    "etc.\n",
    "#Assignment operators\n",
    "assignment:\n",
    "    x=5\n",
    "a =10\n",
    "b =5 \n",
    "a += b #equivalent to a = a+b\n",
    "print (a)\n",
    "#Comparison operators: compare two value and return a boolean result.\n",
    "ex:\n",
    "    equal to(==)\n",
    "    a =5; \n",
    "    b =5;\n",
    "    print (a == b)\n",
    "less than or equal to ('<=')\n",
    "a =5;\n",
    "b =3;\n",
    "print (a <= b)\n",
    "# logical operators\n",
    "#Identuty operators\n",
    "\n",
    "etc.."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1e60b937-d0f8-46b0-998e-134012a7ae72",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Explain the concept of type casting in Python with examples.\n",
    "#Type casting in python refers to converting one data type into another. there are two types of casting:\n",
    "1- Implicit type conversion(automatic)\n",
    "2- Explicit type conversion (manual)\n",
    "ex:\n",
    "    a =5\n",
    "    b =3\n",
    "    c = a+b\n",
    "    (float)\n",
    "    d = a*b\n",
    "  \n",
    "ex:\n",
    "    convert int to float:\n",
    "        a = 5\n",
    "        n =float(a)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "80a8680f-13b9-4b57-855f-235ac44e7d5d",
   "metadata": {},
   "outputs": [],
   "source": [
    "#How do conditional statement work in Python? Illustrate with examples.\n",
    "\n",
    "#Conditional statements in python allow you to execute certain piece of code based on whether a condition is true or false.\n",
    "1- if statement\n",
    "2- if-else statement\n",
    "3-elif statement\n",
    "4-nested if statement\n",
    "\n",
    "ex:\n",
    "    age =21 \n",
    "    if age>=18:\n",
    "        print (\"you will be served alcohal\")\n",
    "        else:\n",
    "            print(\"get out of the bar\")\n",
    "            \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aeb349c9-c73d-4b20-a14e-6c603deaf731",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Describe the different types of loops in Python and their use cases with examples.\n",
    "\n",
    "\n",
    "#In python there are two primary types of loops : for loops and while loops.\n",
    "\n",
    "ex:for loops\n",
    "    iterating over a list\n",
    "    numbers = [1, 2, 3, 4 ,5]\n",
    "    for number in numbers:\n",
    "        print (number)\n",
    "       \n",
    "ex:\n",
    "    while loops\n",
    "    using a while loop to print numbers from 1 to 5 \n",
    "    count = 1\n",
    "    while count <= 5:\n",
    "        print (count)\n",
    "        count += 1\n",
    "        "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
